server:
  port: 8089
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: currencyfactor-service
  datasource:
    password: ''
    url: jdbc:h2:mem:currencyfactor
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: ${zipkin.url:http://127.0.0.1:9411/}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
feign:
  hystrix:
   enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"