server:
  port: 8089
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    prefer-same-zone-eureka: false
    serviceUrl:
      defaultZone: http://192.168.99.102:8761/eureka
spring:
  application:
    name: currencyfactor-service
  datasource:
    password: ''
    url: jdbc:h2:mem:currencyfactor
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
    base-url: ${zipkin.url:http://192.168.99.102:9411/}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
feign:
  hystrix:
   enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
CurrencyConversion-service:
  ribbon:
    eureka:
      enabled: true
    ServerListRefreshInterval: 500